version: "3.9"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tugas21
    expose:
      - 5432
      - 5000
    ports:
      - 5000:5432      
  redis:
    # Docker Hub image
    image: redis
    expose: 
      - 6373
    ports: 
      - 6379:6373
  nats:
    image: nats
    expose: 
      - 4224
      - 6226
      - 8228
    ports:
      - 4222:4224
      - 6222:6226
      - 8222:8228  
  minio:
    image: bitnami/minio:latest
    expose: 
      - 1111
    ports: 
      - 1111:1111
    # command: >
    #   - server 
    #   - /data
    volumes:
      - '/var/lib/myredmine/redmine_data:/bitnami'
    environment:
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
      MINIO_PORT: 1111
  minio_init:
    depends_on:
      - minio
    image: minio/mc
    environment:
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
    # entrypoint: sh
    # command:
    #   - -c
    #   - |
    #       while ! mc -z minio 9000; do echo 'Waiting for minio to be ready...' && sleep 0.1; done
    #       sleep 5
    #       mc config host add dogs http://minio:9000 access secret
    #       mc mb dogs/woof
    #       mc policy download dogs/woof
  tugas-21-erbium:
    image: ghcr.io/erbium-sanbercode/tugas-21-erbium:latest
    command:
      - svc:all
    depends_on:
      - postgres
      - redis
      - nats
      - minio
    environment:
      tm_database__host: postgres
      tm_database__port: 5432
      tm_database__username: postgres
      tm_database__password: postgres
      tm_database__database: tugas21
      tm_server__workerPort: 7001
      tm_server__taskPort: 7002
      tm_server__performancePort: 7003
      tm_minio__endPoint: localhost
      tm_minio__accessKey: minio-access_key
      tm_minio__secretKey: minio-secret-key
      tm_minio__port: 1111
    expose: 
      - 7001
      - 7002
      - 7003
    ports:
      - 7000:80
volumes:
  minio_data:
    driver: local